version: "2"
services:
  ca:
    image: hyperledger/fabric-ca:${CA_TAG}
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - GODEBUG=netdns=go
    - LICENSE=accept
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
  couchdb:
    image: couchdb:${COUCH_TAG}
    environment:
    - GODEBUG=netdns=go
    - LICENSE=accept
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=adminpw
  orderer:
    image: hyperledger/fabric-orderer:${IMAGE_TAG}
    environment:
    - FABRIC_LOGGING_SPEC=DEBUG
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - GODEBUG=netdns=go
    - LICENSE=accept
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
  peer:
    image: hyperledger/fabric-peer:${IMAGE_TAG}
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=bc_fabricnetwork
    - FABRIC_LOGGING_SPEC=DEBUG
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_ENDORSER_ENABLED=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=false
    - CORE_PEER_GOSSIP_ORGLEADER=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - GODEBUG=netdns=go
    - LICENSE=accept
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
