
Organizations:
    - &OrdererOrg
            Name: OrdererMSP
            ID: OrdererMSP
            MSPDir: crypto-config/ordererOrganizations/orderer.net/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('OrdererMSP.member')"
                Writers:
                    Type: Signature
                    Rule: "OR('OrdererMSP.member')"
                Admins:
                    Type: Signature
                    Rule: "OR('OrdererMSP.admin')"

    
    - &BuyerOrg
            Name: BuyerMSP
            ID: BuyerMSP
            MSPDir: crypto-config/peerOrganizations/superbuyer.com/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('BuyerMSP.admin', 'BuyerMSP.peer', 'BuyerMSP.client' )"
                Writers:
                    Type: Signature
                    Rule: "OR('BuyerMSP.admin', 'BuyerMSP.client' )"
                Admins:
                    Type: Signature
                    Rule: "OR('BuyerMSP.admin')"
                Endorsement:
                    Type: Signature
                    Rule: "OR('BuyerMSP.peer')"                
            AnchorPeers:
              - Host: peer0.superbuyer.com
                Port: 7051
    
    - &SellerOrg
            Name: SellerMSP
            ID: SellerMSP
            MSPDir: crypto-config/peerOrganizations/rapidseller.net/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('SellerMSP.admin', 'SellerMSP.peer', 'SellerMSP.client' )"
                Writers:
                    Type: Signature
                    Rule: "OR('SellerMSP.admin', 'SellerMSP.client' )"
                Admins:
                    Type: Signature
                    Rule: "OR('SellerMSP.admin')"
                Endorsement:
                    Type: Signature
                    Rule: "OR('SellerMSP.peer')"                
            AnchorPeers:
              - Host: peer0.rapidseller.net
                Port: 7051
    

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true


Application: &ApplicationDefaults
    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities


Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
          - orderer0.orderer.net:7050
          - orderer1.orderer.net:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 98 MB
        PreferredMaxBytes: 1024 KB
    EtcdRaft:
        Consenters:
          
            - Host: orderer0.orderer.net
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/orderer.net/orderers/orderer0.orderer.net/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/orderer.net/orderers/orderer0.orderer.net/tls/server.crt
           
            - Host: orderer1.orderer.net
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/orderer.net/orderers/orderer1.orderer.net/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/orderer.net/orderers/orderer1.orderer.net/tls/server.crt
           
    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    OrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities 
        Consortiums:
            SupplyChainConsortium:
                Organizations:
                   - *BuyerOrg
                   - *SellerOrg
                   
        
    
    sales:
        Consortium: SupplyChainConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
              - *BuyerOrg
              - *SellerOrg
              
            Capabilities:
              <<: *ApplicationCapabilities
    
        

