OrdererOrgs:
- CA:
    Country: US
    Locality: Nashville
    OrganizationalUnit: IT
    PostalCode: "37235"
    Province: TN
    StreetAddress: 2301 Vanderbilt Pl
  Domain: orderer.net
  Name: Orderer
  Specs:
  - SANS:
    - localhost
  Template:
    Count: 2
    Hostname: orderer{{.Index}}
PeerOrgs:
- CA:
    Country: US
    Hostname: ca
    Locality: Nashville
    OrganizationalUnit: IT
    PostalCode: "37235"
    Province: TN
    StreetAddress: 2301 Vanderbilt Pl
  Domain: superbuyer.com
  EnableNodeOUs: true
  Name: Buyer
  Template:
    Count: 2
    SANS:
    - localhost
  Users:
    Count: 2
- CA:
    Country: US
    Hostname: ca
    Locality: Nashville
    OrganizationalUnit: IT
    PostalCode: "37235"
    Province: TN
    StreetAddress: 2301 Vanderbilt Pl
  Domain: rapidseller.net
  EnableNodeOUs: true
  Name: Seller
  Template:
    Count: 2
    SANS:
    - localhost
  Users:
    Count: 2
